### ISSUE TITLE
Create an arm64 version of this image

### ISSUE THREAD

**Issue by sidick** [walkero-gr/docker4AmigaVBCC#2]
This looks very well put together, but due to running on an ARM MacBook, it's running under emulation, so Is there any chance you could create this as a multi platform image?

Thanks in advance!

**Comment by walkero-gr** [comment]
@sidick I am glad you like these images. For the last few days I am looking at docker buildx. Although I don't have the necessary hardware to test it, I will try to create something. Are you willing to test as soon as it is available?

Also, if you'd like to donate some hardware, don't be shy. Send it over :D :D

**Comment by sidick** [comment]
Definitely willing to test, can't afford to send hardware though I'm afraid 😀
